services:
  - type: web
    name: event-booking-api
    runtime: docker
    dockerfilePath: ./Dockerfile.prod
    plan: free
    healthCheckPath: /api/events
    envVars:
      - key: DB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
